-- =============================================================================
-- ShuleConnect: 002_seed.sql
-- Generic seed — no school-specific data.
-- Schools are created at runtime via the onboarding flow when a new
-- administrator signs up.
-- Run AFTER 001_schema.sql
-- =============================================================================


-- =============================================================================
-- HOW TO PROVISION THE FIRST SCHOOL ADMIN
-- =============================================================================
--
-- Option A — Self-service (recommended)
--   1. Open the app and click "Sign Up".
--   2. Enter your name, email, and password.
--   3. You will be redirected to the onboarding page.
--   4. Fill in your school name, country, and city, then click
--      "Create School & Continue".
--   5. Your account is created as school_admin and you land on the dashboard.
--
-- Option B — Manual via Supabase Dashboard (for super_admin provisioning)
--   STEP 1 — Create the auth user
--     Dashboard > Authentication > Users > "Add user"
--     Supply the admin's email address and a temporary password.
--     Copy the UUID that Supabase assigns (shown in the user list).
--
--   STEP 2 — Insert the school
--     INSERT INTO schools (name, slug, country)
--     VALUES ('Your School Name', 'your-school-slug', 'Tanzania')
--     RETURNING id;
--
--   STEP 3 — Insert the profile
--     INSERT INTO profiles (id, school_id, full_name, email, role)
--     VALUES (
--       '<UUID from step 1>',
--       '<school id from step 2>',
--       'Admin Full Name',
--       'admin@yourschool.ac',
--       'school_admin'
--     );
--
--   STEP 4 — Seed allowed message pairs
--     SELECT seed_allowed_message_pairs('<school id from step 2>');
--
-- NOTES:
--   * The 'super_admin' role bypasses school_id filtering and can manage
--     all schools. Only assign it to platform operators, not school staff.
--   * student_teacher_messaging is FALSE by default. Toggle it via the
--     Settings page in the app, or update the schools and allowed_message_pairs
--     tables directly.
--   * parental_consents is append-only (UPDATE/DELETE blocked by SQL rules).
--     Record revocations by inserting a new row with granted = false.
-- =============================================================================
